### ISSUE TITLE
Integration broken after upgrade

### ISSUE THREAD

**Issue by cvinhaes** [jason0x43/hacs-hubitat#269]
**Describe the bug**
Receiving the following error after upgrading from v9.8 to v9.25 (tested with 9.26, same issue):
ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration hubitat: Unable to import component: cannot import name 'UTC' from 'datetime' (/usr/local/lib/python3.10/datetime.py)

**To Reproduce**
start with a working configuration of home assistant v2023.4, hacs-hubitat v9.8 and hubitat C5 v2.3.8.134.
use HACS to upgrade the hubitat integration component to v9.25
now I receive the error in the log and the integrations won't load.

**Screenshots**

no screen message, just logged error.

**Environment**

 - Home Assistant version: 
 - Integration version:

**Comment by jason0x43** [comment]
You’re running HA 2023.4?

**Comment by cvinhaes** [comment]
That is correct:

![Capturar](https://github.com/jason0x43/hacs-hubitat/assets/50474774/e669a761-7c1f-4b58-86a4-2a1e2458b4b6)



> You’re running HA 2023.4?

**Comment by cvinhaes** [comment]
Nevermind, I've updated HA to 2023.12 and now it works. I could just no find the version compatibility chart anywhere in the docs, but maybe I missed it.

**Comment by jason0x43** [comment]
Unfortunately the extension's version compatibility isn't well defined. I've been testing against current HA and HA from 3 months ago. I should probably at least shoot for supporting the last 6 months, but I don't want to end up maintaining a bunch of different code paths for different versions of HA. 🙂

**Comment by cvinhaes** [comment]
Hey, no worries! This integration is a huge life saver for me and I cannot complain at all. Before that I was using a lot of http calls do have the same job done. 100% functional after upgrading HA to v 2023.12, thanks for making it available.
