### ISSUE TITLE
Sudden failure to initialize

### ISSUE THREAD

**Issue by acato** [jason0x43/hacs-hubitat#326]
All of a sudden it stopped initializing the integration. I did not notice if it was after upgrading to 0.10.0pre1 but it started happening soon after the upgrade.

Logs:

Logger: homeassistant.config_entries
Source: config_entries.py:762
First occurred: 2:16:14 AM (3 occurrences)
Last logged: 5:13:18 PM

Error setting up entry Hubitat (c75a0d65) for hubitat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubitat/__init__.py", line 81, in async_setup_entry
    await asyncio.wait_for(hub.async_connect(), timeout=STARTUP_CONNECT_TIMEOUT)
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/config/custom_components/hubitat/hub.py", line 621, in async_connect
    _migrate_entity_unique_ids(self.hass, self.id, self.token)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubitat/hub.py", line 874, in _migrate_entity_unique_ids
    if entity.unique_id and entity.unique_id.startswith(old_prefix):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'startswith'

**Comment by jason0x43** [comment]
Hmmm...that's saying that `entity.unique_id` is an integer, which should never be the case.

I released v0.10.0-pre2. That should at least allow the integration to start up, and will also log some additional information during entity id migration. Try turning on debug logging for the integration and reboot, and see if there are any messages like "Skipping entity X with non-str unique_id".

**Comment by acato** [comment]
The issue was a weird one. There was a configuration syntax issue with the WAQI air quality sensors, that for some reason were picked up by the Hubitat extension. Pre-2 and fixing the config file removed the issue. Thanks for looking into it.
